### ISSUE TITLE
preexec:1: bad math expression: operator expected at `N/1000000' (mac m1)

### ISSUE THREAD

**Issue by albertmg** [liamg/bearings#3]
After installing this, every command submitted throws this error: 
`preexec:1: bad math expression: operator expected at 'N/1000000' (mac m1)`

The reason is **date** command on mac doesn't support the `%N` flag, so there are mainly 2 solutions:

- Run `brew install coreutils` to install the default date command and change in .zshrc the **date** command for **gdate**
- Remove the `%N` flag and modify the code accordingly.

Hope that helps!

**Comment by liamg** [comment]
Thanks @albertmg , goiod catch! I guess I can check if the OS is MacOS and only use second-accuracy if so.
